added a confirmation line if first hour was sucessfully run, to replace the "STOP 13" which was replaced.

diff --git a/exec/setup_e b/exec/setup_e
--- a/exec/setup_e
+++ b/exec/setup_e
@@ -11,7 +11,7 @@
 ##   - extra link from /u/cmrun to rundir
 ##   - output of WARN.f90 if compilation not successful 
 ##   - added search for data files in /u/cmrun
-##   - PROBLEM: $retc does not take STOP nn as the correct return code. Ideas?
+##   - PROBLEM: $retc does not take STOP nn as the correct return code. Fixed
 ##   - changed files from numbers to names
 ##
    df /raid1 /raid2 /raid3 /raid4 > /dev/null
@@ -177,8 +177,11 @@
    retc=$?
    rm -f AIC GIC OIC  #fort.[789]
    "$RUNID"uln
-   if [[ $retc -ne 0 && $retc -ne 13 && $retc -ne 12 ]] then
-     echo Problem encountered while running hour 1; exit 4 ; fi
+   if [[ $retc -ne 13 && $retc -ne 12 ]] then
+     echo Problem encountered while running hour 1; exit 4 ; 
+   else
+     echo 1st hour completed sucessfully
+   fi
 
 ## move printout to M-disk after successful initialization
    if [[ $PRT = [Pp]* ]] then /u/exec/prt ${RUNID} ; fi
