Committing a generic cubed-sphere to latlon remapping program. The remap file now supplies all necessary info.  A 2nd-order method is available, but disabled until the interface is refined to allow the options for the 2nd-order method to be specified.

diff --git a/model/mk_diags/compscr b/model/mk_diags/compscr
--- a/model/mk_diags/compscr
+++ b/model/mk_diags/compscr
@@ -96,9 +96,11 @@ $cmpcmd  || exit  # terminate the script if any compilation fails
 rm -f driver.f
 
 #
-# Compile the generic summation routine
+# Compile the generic summation and cs->latlon regridding routines
 #
-progname=sumfiles
-cmpcmd="${fccmd} miscnc.f ${progname}.f -o ${progname} ${ncinc} ${nclib}"
-echo $cmpcmd
-$cmpcmd  || exit  # terminate the script if any compilation fails
+for progname in sumfiles csregrid
+do
+  cmpcmd="${fccmd} miscnc.f ${progname}.f -o ${progname} ${ncinc} ${nclib}"
+  echo $cmpcmd
+  $cmpcmd  || exit  # terminate the script if any compilation fails
+done
